[haproxy]
vm-haproxy ansible_host=158.158.120.68 ansible_user=azureuser

[microservices]
vm-microservices ansible_host=68.221.70.132 ansible_user=azureuser

[all:vars]
dockerhub_user=joseligo
image_tag=v1.0
